In [1]:
import numpy as np

In [2]:
# creating 1-D arrays, vector
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [3]:
# creating 2-D array, matrix
array_b=np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# array N-Dimensional, with N an integer
# the array function is just a name, it allows to create N-dimensional arrays
array_c = np.array([1,2,3])

In [5]:
array_c

array([1, 2, 3])

In [6]:
type(array_c)

numpy.ndarray

In [8]:
array_c.shape # (rows, columns), 1-D array returns just the length

(3,)

In [11]:
array_d=np.array([[7,8,9],[10,11,12]])
array_d.shape # each row is an array, each value is a column

(2, 3)

In [13]:
array_d.shape[1]

3

In [19]:
array_e=np.array(13) # escalar, just a number
type(array_e)
print(array_e)

13


In [21]:
array_e.shape # no length or shape

()

In [22]:
array_f = np.array([15])
type(array_f)

numpy.ndarray

In [23]:
array_f.shape # 1 single row with a single column, 1x1 matrix

(1,)