In [2]:
import numpy as np

In [3]:
# creating 1-D arrays, vector
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [4]:
# creating 2-D array, matrix
array_b=np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# array N-Dimensional, with N an integer
# the array function is just a name, it allows to create N-dimensional arrays
array_c = np.array([1,2,3])

In [6]:
array_c

array([1, 2, 3])

In [7]:
type(array_c)

numpy.ndarray

In [8]:
array_c.shape # (rows, columns), 1-D array returns just the length

(3,)

In [9]:
array_d=np.array([[7,8,9],[10,11,12]])
array_d.shape # each row is an array, each value is a column

(2, 3)

In [10]:
array_d.shape[1]

3

In [11]:
array_e=np.array(13) # escalar, just a number
type(array_e)
print(array_e)

13


In [12]:
array_e.shape # no length or shape

()

In [13]:
array_f = np.array([15])
type(array_f)

numpy.ndarray

In [14]:
array_f.shape # 1 single row with a single column, 1x1 matrix

(1,)

### Indexing

In [15]:
array_a=np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
array_a[0]
array_a[1,0] # equal to array_a[1][0]

4

In [17]:
array_a[:,1] # returns [2,5] the column 1, it's important to put the comma
array_a[:1] # otherwise it returns only the last row

array([[1, 2, 3]])

### using negative indexes

In [18]:
array_b=np.array([[1,2,3],[4,5,6]])
array_b[-1]

array([4, 5, 6])

In [19]:
array_b[1,-1]

6

In [20]:
array_b[:,-1]
array_b[:-1]

array([[1, 2, 3]])

### assigning values

In [21]:
array_b[1,2]=100 # [1][2] element is now 100
array_b

array([[  1,   2,   3],
       [  4,   5, 100]])

In [22]:
array_b[0]=11 # assigns 11 to all element in the 0 row
array_b

array([[ 11,  11,  11],
       [  4,   5, 100]])

In [23]:
array_b[:,1]=99
array_b

array([[ 11,  99,  11],
       [  4,  99, 100]])

In [24]:
list_x=[8,7,8]
array_b[0]=list_x
array_b[0]

array([8, 7, 8])

In [25]:
array_b[:]=9
array_b

array([[9, 9, 9],
       [9, 9, 9]])

In [26]:
array_b = array_b.astype(complex)
array_b

array([[9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j]])

In [32]:
array_b = np.array([[9.+0.j, 9.+0.j, 9.+0.j],
      [9.+0.j, 9.+0.j, 9.+0.j]], dtype=np.str_)
array_b

array([['(9+0j)', '(9+0j)', '(9+0j)'],
       ['(9+0j)', '(9+0j)', '(9+0j)']], dtype='<U6')