In [41]:
import numpy as np

In [42]:
# creating 1-D arrays, vector
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [43]:
# creating 2-D array, matrix
array_b=np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# array N-Dimensional, with N an integer
# the array function is just a name, it allows to create N-dimensional arrays
array_c = np.array([1,2,3])

In [45]:
array_c

array([1, 2, 3])

In [46]:
type(array_c)

numpy.ndarray

In [47]:
array_c.shape # (rows, columns), 1-D array returns just the length

(3,)

In [48]:
array_d=np.array([[7,8,9],[10,11,12]])
array_d.shape # each row is an array, each value is a column

(2, 3)

In [49]:
array_d.shape[1]

3

In [50]:
array_e=np.array(13) # escalar, just a number
type(array_e)
print(array_e)

13


In [51]:
array_e.shape # no length or shape

()

In [52]:
array_f = np.array([15])
type(array_f)

numpy.ndarray

In [53]:
array_f.shape # 1 single row with a single column, 1x1 matrix

(1,)

### Indexing

In [54]:
array_a=np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
array_a[0]
array_a[1,0] # equal to array_a[1][0]

4

In [56]:
array_a[:,1] # returns [2,5] the column 1, it's important to put the comma
array_a[:1] # otherwise it returns only the last row

array([[1, 2, 3]])

### using negative indexes

In [57]:
array_b=np.array([[1,2,3],[4,5,6]])
array_b[-1]

array([4, 5, 6])

In [58]:
array_b[1,-1]

6

In [59]:
array_b[:,-1]
array_b[:-1]

array([[1, 2, 3]])

### assigning values

In [60]:
array_b[1,2]=100 # [1][2] element is now 100
array_b

array([[  1,   2,   3],
       [  4,   5, 100]])

In [61]:
array_b[0]=11 # assigns 11 to all element in the 0 row
array_b

array([[ 11,  11,  11],
       [  4,   5, 100]])

In [62]:
array_b[:,1]=99
array_b

array([[ 11,  99,  11],
       [  4,  99, 100]])

In [63]:
list_x=[8,7,8]
array_b[0]=list_x
array_b[0]

array([8, 7, 8])

In [66]:
array_b[:]=9
array_b

array([[9, 9, 9],
       [9, 9, 9]])